name: Test and Publish

on:
  push:
    branches:
      - main

jobs:
  test-n-publish:
    permissions:
      contents: write
      packages: write

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            bflag: --mac
          - os: windows-latest
            bflag: --win
          - os: ubuntu-latest
            bflag: --linux

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 18.3.0
          cache: npm

      - name: npm install
        run: |
          npm install

      - name: npm test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package
          npm run lint
          npm exec tsc
          npm test
      - name: npm run build
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always ${{ matrix.bflag }}
